protector.config:
  type: config_object
  label: 'Protector config'
  mapping:
    login:
      type: string
      label: 'Login'
    password:
      type: string
      label: 'Password'
    state:
      type: boolean
      label: 'Is Active'